apiVersion: v1
kind: Service
metadata:
  labels:
    k8s-app: gke-prober
  name: gke-prober
  namespace: gke-prober-system
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8081
  selector:
    k8s-app: gke-prober
  type: LoadBalancer